apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: test-ilab-02
  janus-idp.io/tekton: test-ilab-02
  backstage.io/kubernetes-id: test-ilab-02
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: test-ilab-02
resources: 
- initialize-namespace.yaml
- rhoai/
